---
abstract: 'Create CPAN::Mini mirrors with the archives extracted'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CPAN::Mini::Extract
name: CPAN-Mini-Extract
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Archive::Tar: 1.22
  CPAN::Mini: 0.550
  File::Find::Rule: 0.30
  File::Remove: 0.34
  File::Spec: 0.80
  File::Temp: 0
  IO::Uncompress::Gunzip: 0
  LWP::Online: 0.03
  List::Util: 1.15
  Params::Util: 1.00
  URI: 0
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/CPAN-Mini-Extract
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/CPAN-Mini-Extract
version: 1.21
