name: CPAN-Mini-Extract
version: 0.13
abstract: Create CPAN::Mini mirrors with the archives extracted
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
requires:
  perl: 5.6.0
  Carp: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0.80
  File::Remove: 0.24
  File::Find::Rule: 0.27
  List::Util: 1.15
  IO::File: 0
  IO::Zlib: 1.04
  Archive::Tar: 1.22
  Params::Util: 0.06
  CPAN::Mini: 0.40
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
