---
abstract: 'Create CPAN::Mini mirrors with the archives extracted'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: CPAN::Mini::Extract
name: CPAN-Mini-Extract
no_index:
  directory:
    - inc
    - t
requires:
  Archive::Tar: 1.22
  CPAN::Mini: 0.550
  File::Find::Rule: 0.30
  File::Remove: 0.34
  File::Spec: 0.80
  File::Temp: 0
  IO::Uncompress::Gunzip: 0
  LWP::Online: 0.03
  List::Util: 1.15
  Params::Util: 0.20
  URI: 0
  perl: 5.6.0
version: 1.20
